version: "3"

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      asixnetwork:
        ipv4_address: 192.168.0.6
    depends_on: 
      - dns

  dns:
    build:
      context: .
      dockerfile: dns/Dockerfile
    ports:
      - "8082:53"
    networks:
      asixnetwork:
        ipv4_address: 192.168.0.7

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "BBDDLibrary"
      MYSQL_PASSWORD: "password"
    ports:
      - "8083:3306"
    networks:
      asixnetwork:
        ipv4_address: 192.168.0.8
    volumes:
      - './sql/BBDDLibrary.sql:/docker-entrypoint-initdb.d/BBDDLibrary.sql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8084:80"
    networks:
      asixnetwork:
        ipv4_address: 192.168.0.9
    depends_on:
      - mysql

networks:
  asixnetwork:
    ipam:
      config:
        - subnet: 192.168.0.0/24
