-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost
-- Tiempo de generación: 24-04-2023 a las 16:11:58
-- Versión del servidor: 10.4.24-MariaDB
-- Versión de PHP: 7.4.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `BBDDLibrary`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `Books`
--

CREATE TABLE `books` (
  `book_id` int(11) NOT NULL,
  `book_title` varchar(250) NOT NULL,
  `author_name` varchar(100) NOT NULL,
  `book_description` varchar(1000) DEFAULT NULL,
  `book_photo` varchar(1000) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Volcado de datos para la tabla `Books`
--

INSERT INTO `books` (`book_id`, `book_title`, `author_name`, `book_description`, `book_photo`) VALUES
(1, 'Pride and Prejudice', 'Jane Austen', 'Pride and Prejudice is a classic novel by Jane Austen. It follows the story of Elizabeth Bennet, a headstrong and independent young woman, and her tumultuous relationship with Mr. Darcy, a wealthy and proud gentleman. Set in 19th century England, the novel explores themes of love, marriage, social class, and societal expectations. With its witty dialogue, memorable characters, and enduring romance, Pride and Prejudice is considered one of the greatest works of English literature.', NULL),
(2, '1984', 'George Orwell', '1984 is a dystopian novel by George Orwell. It depicts a totalitarian society ruled by the Party, led by Big Brother, where individualism and freedom are suppressed. The story follows Winston Smith, a disillusioned Party member, who rebels against the oppressive regime. Through vivid descriptions and thought-provoking concepts, Orwell explores the dangers of totalitarianism, censorship, and surveillance. 1984 is a chilling portrayal of a bleak future, warning about the consequences of unchecked government control and the loss of individuality.', NULL),
(3, 'Crime and Punishment', 'Fyodor Dostoevsky', 'Crime and Punishment by Fyodor Dostoevsky is a classic novel that delves into the psychological struggles of its protagonist, Raskolnikov. He is a poor ex-student in Saint Petersburg who commits a heinous crime and battles with guilt and morality. Set against the backdrop of 19th-century Russia, the novel explores the complexities of human nature, the consequences of crime, and the search for redemption. Dostoevskys masterful writing captures the inner turmoil of Raskolnikov, making Crime and Punishment a timeless work that delves into the darkest corners of the human mind.', NULL),
(4, 'Hamlet', 'William Shakespeare', 'Hamlet by William Shakespeare is a tragedy that follows the story of the titular character, Prince Hamlet of Denmark. After his fathers death and his mothers hasty remarriage, Hamlet is consumed by grief and seeks revenge for his fathers murder. The play is renowned for its exploration of themes such as betrayal, revenge, and the complexity of human nature. Hamlets internal struggles, his soliloquies, and his interactions with other characters are masterfully crafted, making Hamlet one of Shakespeares most iconic works, revered for its depth and complexity.', NULL),
(5, 'One Hundred Years of Solitude', 'Gabriel García Márquez', 'One Hundred Years of Solitude is a novel by Gabriel García Márquez, first published in 1967. The book tells the story of the Buendía family and their seven generations living in the fictional town of Macondo. It explores themes of family, love, magic, and the cyclical nature of time. The novel is considered a masterpiece of magical realism and has influenced many writers.', NULL),
(6, 'Anna Karenina', 'Leo Tolstoy', 'Anna Karenina is a novel by the Russian writer Leo Tolstoy, first published in 1877. The book tells the story of Anna, a married aristocrat who embarks on a passionate affair with a dashing cavalry officer, Count Vronsky. As Anna struggles to balance her love for Vronsky with her responsibilities as a wife and mother, she becomes increasingly isolated and vulnerable to the judgment and scrutiny of society. Tolstoys masterpiece is a rich and complex exploration of love, morality, and the human condition, and is widely regarded as one of the greatest novels ever written.', NULL),
(7, 'The Odyssey', 'Homer', 'The Odyssey is an epic poem written by the ancient Greek poet Homer, around the 8th century BCE. It tells the story of Odysseus, a hero of the Trojan War, who faces a series of obstacles on his journey home to Ithaca, including battles with monsters and the wrath of the gods. Along the way, he must also confront the betrayal of his wife Penelope and the disloyalty of his subjects. The Odyssey is a classic tale of adventure, heroism, and the struggle for survival, and is considered one of the foundational works of Western literature.', NULL),
(8, 'The Stranger', 'Albert Camus', 'The Stranger is a novel by Albert Camus, published in 1942. It tells the story of Meursault, a detached and emotionless French Algerian who kills an Arab man and faces a trial that ultimately exposes his lack of societal conformity and moral ambiguity. The novel explores themes of absurdity, existentialism, and the human condition, and has become a classic of modern literature.', NULL),
(9, 'The Brothers Karamazov', 'Fyodor Dostoevsky', 'The Brothers Karamazov is a novel by Russian author Fyodor Dostoevsky, first published in 1880. The story revolves around the lives of the Karamazov brothers: Dmitry, Ivan, and Alexei, and their dysfunctional family dynamic, complicated by themes of religion, morality, and existentialism. The novel is considered one of Dostoevskys greatest works and explores complex philosophical concepts while providing a vivid depiction of Russian society during the 19th century.', NULL),
(10, 'Great Expectations', 'Charles Dickens', 'Great Expectations is a classic novel by Charles Dickens, first published in 1861. The story follows Pip, a young orphan boy who dreams of becoming a gentleman and winning the heart of his unattainable love, Estella. Along the way, he encounters a colorful cast of characters, including the eccentric Miss Havisham and the convict Magwitch. Through Pips journey, the novel explores themes of social class, identity, and redemption, making it a timeless masterpiece of English literature.', NULL),
(11, 'Lolita', 'Vladimir Nabokov', 'Lolita is a novel by Vladimir Nabokov, published in 1955. It follows the story of a middle-aged literature professor who becomes obsessed with a 12-year-old girl named Dolores Haze, whom he nicknames Lolita. The novel explores themes of desire, power, and obsession, and has been the subject of much controversy due to its subject matter. Nabokovs writing style is known for its intricate wordplay and vivid imagery, making Lolita a challenging but rewarding read.', NULL),
(12, 'The Old Man and the Sea', 'Ernest Hemingway', 'The Old Man and the Sea is a short novel written by Ernest Hemingway. It tells the story of an aging fisherman named Santiago, who has gone 84 days without catching a fish. On the 85th day, he sets out alone in his small skiff to the Gulf Stream, where he hooks a giant marlin. The rest of the book is a battle between the old man and the fish as they struggle against each other and the forces of nature. Despite the old mans determination, he eventually loses the battle, but he returns to shore with a sense of accomplishment and renewed strength. The novel explores themes of perseverance, resilience, and the struggle against nature and oneself.', NULL),
(13, 'War and Peace', 'Leo Tolstoy', 'War and Peace is a novel by Leo Tolstoy that chronicles the history of the French invasion of Russia and the impact of the Napoleonic era on Tsarist society through the stories of five Russian aristocratic families. It is a sprawling epic that explores themes of love, war, power, and the struggle for personal and societal identity in the face of historical upheaval. The novel is famous for its intricate character development, philosophical insights, and vivid depictions of historical events. It is considered one of the greatest works of literature in the Western canon.', NULL),
(14, 'Don Quixote', 'Miguel de Cervantes Saavedra', 'Don Quixote is a novel by Spanish author Miguel de Cervantes. First published in 1605, the book tells the story of an aging gentleman who becomes so enamored with tales of chivalry and knights that he sets out on a quest to become a knight himself. Along with his loyal squire, Sancho Panza, Don Quixote embarks on a series of misadventures, often mistaking reality for fantasy. The book is celebrated for its humorous portrayal of Don Quixotes delusions and its commentary on the nature of reality and perception. It is considered a masterpiece of Western literature and has been widely translated and adapted into other forms of media.', NULL),
(15, 'The Iliad', 'Homer', 'The Iliad is an epic poem written by the ancient Greek poet Homer. It tells the story of the Trojan War, focusing on the fierce battles between the Greeks and the Trojans, and the heroic deeds of legendary warriors such as Achilles and Hector. The poem is also a meditation on the themes of honor, glory, and fate, and has been celebrated for its powerful portrayal of the human condition. The Iliad remains a seminal work of Western literature and continues to inspire readers with its timeless themes and vivid storytelling.', NULL),
(16, 'Madame Bovary', 'Gustave Flaubert', 'Madame Bovary is a novel by Gustave Flaubert, first published in 1856. The story follows Emma Bovary, a young woman who marries a dull country doctor and quickly becomes disillusioned with her life. She seeks passion and excitement through extramarital affairs and consumerism, but eventually, her actions lead to tragedy. Flauberts precise prose and psychological insight make Madame Bovary a masterpiece of realism and a landmark in the development of the modern novel.', NULL),
(17, 'The Trial', 'Franz Kafka', 'The Trial is a novel by Franz Kafka that tells the story of a man named Josef K. who is arrested and put on trial for a crime that is never revealed to him. As he navigates the opaque and bureaucratic legal system, he becomes increasingly desperate to prove his innocence, but ultimately succumbs to the overwhelming power of the court. The novel explores themes of guilt, justice, and the arbitrary nature of authority, and has been widely interpreted as a commentary on the dehumanizing effects of modern society.', NULL),
(18, 'The Divine Comedy', 'Dante Alighieri', 'The Divine Comedy is an epic poem by Italian writer Dante Alighieri, written in the early 14th century. It describes Dantes journey through Hell, Purgatory, and Heaven, guided by the poet Virgil and his beloved Beatrice. The poem is divided into three parts, each consisting of 33 cantos, with an additional introductory canto. The Divine Comedy is considered one of the greatest works of Western literature, and is renowned for its complex allegorical symbolism, vivid imagery, and exploration of moral and theological themes.', NULL),
(19, 'Moby-Dick or, the Whale', 'Herman Melville', 'Moby-Dick or, the Whale is a novel written by Herman Melville in 1851. The book follows the story of Ishmael, a sailor who joins the crew of the Pequod, a whaling ship captained by Ahab. Ahab is obsessed with finding and killing Moby Dick, a white sperm whale that had previously taken his leg. The novel explores themes of revenge, obsession, fate, and the relationship between man and nature. It is considered a classic of American literature and has been adapted into numerous films, plays, and other media.', NULL),
(20, 'King Lear', 'William Shakespeare', 'King Lear is a tragedy by William Shakespeare, believed to have been written between 1603 and 1606. The play tells the story of King Lear, who decides to divide his kingdom among his three daughters based on how much they profess to love him. However, his decision leads to chaos and ultimately his own downfall, as he realizes too late the true nature of his daughters and the consequences of his actions. The play explores themes of family, power, loyalty, betrayal, and the consequences of rash decisions.', NULL),
(21, 'Love in the Time of Cholera', 'Gabriel García Márquez', 'Love in the Time of Cholera is a novel by Gabriel García Márquez that explores the enduring power of love. Set in an unnamed city in Colombia during the late 1800s to early 1900s, the story follows the lives of Florentino Ariza and Fermina Daza, two young lovers separated by societal expectations and circumstances. Despite Fermina marrying another man, Dr. Juvenal Urbino, Florentino remains devoted to her and spends over 50 years waiting for his chance to win her back. The novel explores themes of love, aging, death, and the passage of time, all set against the backdrop of a cholera epidemic.', NULL),
(22, 'The Complete Fairy Tales', 'Hans Christian Andersen', 'The Complete Fairy Tales is a collection of stories by Hans Christian Andersen, including classics like The Little Mermaid and The Ugly Duckling. These tales explore themes of love, loss, and transformation through vivid characters and magical settings. With beautiful illustrations and timeless messages, this book has captivated readers of all ages for generations.', NULL),
(23, 'Mrs. Dalloway', 'Virginia Woolf', 'Mrs. Dalloway is a novel written by Virginia Woolf that explores a day in the life of Clarissa Dalloway, an upper-class woman in post-World War I London. The narrative jumps between Clarissas thoughts and those of other characters, including her husband, her former lover, and a shell-shocked veteran. The novel examines themes of social class, gender roles, mental health, and the effects of war on society. Woolfs use of stream-of-consciousness narration and shifting perspectives make Mrs. Dalloway a landmark of modernist literature.', NULL),
(24, 'Othello', 'William Shakespeare', 'Othello is a tragedy written by William Shakespeare around 1603. The play tells the story of Othello, a Moorish general in the Venetian army, and his downfall as a result of jealousy and manipulation by his envious and deceitful ensign, Iago. Othellos marriage to Desdemona, a white Venetian woman, is also a source of conflict and controversy throughout the play. Othello explores themes of love, jealousy, racism, and betrayal, and is considered one of Shakespeares greatest works.', NULL),
(25, 'The Arabian Nights', 'Anonymous', 'The Arabian Nights, also known as One Thousand and One Nights, is a collection of Middle Eastern and South Asian folk tales compiled in Arabic during the Islamic Golden Age. The tales feature a wide range of characters and themes, including magic, love, betrayal, and adventure. The most famous stories within the collection include Aladdin Wonderful Lamp, Ali Baba and the Forty Thieves, and Sindbad the Sailor The tales have been translated into many languages and adapted into various forms of media, including movies, television shows, and video games.', NULL),
(26, 'Ulysses', 'James Joyce', 'Ulysses is a complex and experimental novel by James Joyce, first published in 1922. Set in Dublin, Ireland, on June 16, 1904, it follows the day in the life of Leopold Bloom and Stephen Dedalus, as they go about their daily business and encounter a variety of characters and situations. The novel employs a range of literary techniques, including stream of consciousness narration and non-linear storytelling, and explores themes such as identity, sexuality, and the nature of consciousness. Ulysses is considered one of the most important and influential works of modernist literature.', NULL),
(27, 'The Sound and the Fury', 'William Faulkner', 'The Sound and the Fury is a novel by William Faulkner, first published in 1929. It is known for its unconventional narrative structure and complex themes, including the decline of the South, the dissolution of the Compson family, and the impact of time on human experience. The book is divided into four sections, each narrated by a different character, and explores the inner lives of the Compson family members, particularly their obsession with their own past and their inability to move forward.', NULL),
(28, 'The Canterbury Tales', 'Nevill Coghill', 'The Canterbury Tales is a collection of stories written in Middle English by Geoffrey Chaucer in the late 14th century. The book tells the stories of a diverse group of pilgrims who travel from London to the shrine of Saint Thomas Becket at Canterbury Cathedral. Each pilgrim tells a tale, and these stories range from bawdy and comedic to tragic and moralistic. Through these tales, Chaucer provides a vivid picture of medieval life, customs, and values. The Canterbury Tales is considered one of the greatest works of English literature and a cornerstone of the Western literary canon.', NULL),
(29, 'Gulliver\s Travels: Travels into Several Remote Nations of the World.', 'Jonathan Swift', 'Gullivers Travels is a satirical novel by Jonathan Swift, first published in 1726. The book follows the travels of Lemuel Gulliver to four fictional nations: Lilliput, Brobdingnag, Laputa, and the land of the Houyhnhnms. Through Gullivers encounters with the inhabitants of these lands, Swift offers a critical commentary on human nature and society, as well as on politics, religion, and science. The novel has remained a classic of English literature, famous for its wit, humor, and imaginative world-building.', NULL),
(30, 'Oedipus Rex (The Theban Plays, #1)', 'Sophocles', 'Oedipus Rex, the first of the Theban Plays, is a tragedy written by Sophocles around 429 BC. The play tells the story of Oedipus, a man who unknowingly kills his father and marries his mother, fulfilling a prophecy that he had tried to avoid. As he seeks to uncover the truth about his past and solve the mystery of a plague ravaging his city, Oedipus is ultimately brought to a tragic and devastating realization of his own fate. The play explores themes of fate, free will, and the consequences of ones actions, and has had a profound impact on Western literature and thought.', NULL),
(31, 'The Idiot', 'Fyodor Dostoevsky', 'The Idiot is a novel written by Russian author Fyodor Dostoevsky. It tells the story of Prince Myshkin, a kind and compassionate man who returns to St. Petersburg after being treated for epilepsy in Switzerland. He becomes entangled in a love triangle with two women, Nastasya Filippovna and Aglaya Yepanchin, as he navigates the complex and often corrupt social hierarchy of 19th century Russia. The novel explores themes of morality, love, and the struggle for personal identity in a society that values wealth and status above all else.', NULL),
(32, 'Swann’s Way', 'Marcel Proust', 'Swanns Way is the first volume of Marcel Prousts literary masterpiece, In Search of Lost Time. Published in 1913, it follows the narrators memories of his childhood and his encounters with the aristocratic Swann and his lover, Odette. Through introspection and poetic prose, Proust explores themes of memory, time, love, and societal conventions in early 20th-century France. The books vivid descriptions and complex characters have made it a cornerstone of modern literature.', NULL),
(33, 'Pippi Longstocking (Pippi Långstrump, #1)', 'Astrid Lindgren', '
Pippi Longstocking is a beloved childrens book written by Swedish author Astrid Lindgren. It tells the story of a young girl with red pigtails, superhuman strength, and a wild imagination who lives in a house called Villa Villekulla with her pet monkey and horse. Pippis quirky adventures, her unconventional outlook on life, and her strong sense of justice make her an endearing character for readers of all ages. The book has been translated into over 70 languages and has been adapted into numerous TV series, films, and stage productions.', NULL),
(34, 'The Collected Tales of Edgar Allan Poe', 'Edgar Allan Poe', 'The Collected Tales of Edgar Allan Poe is a compilation of short stories and poems written by the famous American author. The book features Poes renowned works, including The Tell-Tale Heart, The Fall of the House of Usher, and The Raven. His tales often delve into themes of horror, mystery, and the macabre, drawing readers into his dark and atmospheric worlds. The collection showcases Poes exceptional writing style, known for its intricate language and vivid imagery, making it a timeless classic in the literary world.', NULL),
(35, 'To the Lighthouse', 'Virginia Woolf', 'To the Lighthouse is a novel by Virginia Woolf that explores the inner lives and relationships of a family over the course of several years. Set in early 20th century England, the book uses stream-of-consciousness narration to delve into the characters thoughts and emotions as they confront the challenges of daily life and the shifting social norms of the time. With its experimental style and emphasis on subjective experience, To the Lighthouse is a landmark of modernist literature and a poignant meditation on the complexities of human connection', NULL),
(36, 'Faust, First Part', 'Johann Wolfgang von Goethe', 'Faust, First Part is a tragic play written by Johann Wolfgang von Goethe. The story follows the character of Faust, a disillusioned scholar who sells his soul to the devil in exchange for unlimited knowledge and worldly pleasures. Faust becomes infatuated with a young woman named Gretchen, and his pact with the devil leads to tragic consequences for both of them. The play explores themes of temptation, redemption, and the consequences of unchecked ambition.', NULL),
(37, 'Beloved', 'Toni Morrison', 'Beloved is a novel by Toni Morrison that tells the story of Sethe, a former slave who escaped to Ohio with her children but is haunted by the memory of her baby daughter whom she killed to prevent her from being recaptured. Sethes house is then visited by a mysterious young woman named Beloved, who may be the embodiment of her deceased daughter. The novel explores themes of slavery, trauma, memory, and the search for identity and freedom. Morrisons powerful prose and vivid imagery make Beloved a haunting and unforgettable reading experience.', NULL),
(38, 'Blindness', 'José Saramago', '
Blindness is a novel written by Portuguese author José Saramago. The story depicts a sudden epidemic of blindness that spreads throughout an unnamed city. The protagonist, an ophthalmologists wife, is one of the few who does not go blind and becomes the guide for a group of blind people. The novel explores the psychological and social consequences of the epidemic, including the breakdown of social norms, the struggle for survival, and the loss of individuality. Saramagos unique writing style, which includes long sentences and lack of punctuation, adds to the chaotic and disorienting atmosphere of the story.', NULL),
(39, 'Things Fall Apart (The African Trilogy, #1)', 'Chinua Achebe', 'Things Fall Apart is the first book in Chinua Achebes African Trilogy, which tells the story of an Igbo warrior named Okonkwo and his life before and after the arrival of European colonizers in Nigeria. The novel portrays the clash between traditional Igbo culture and the forces of colonialism, leading to Okonkwos downfall and the tragic disintegration of his community. Through vivid characters and evocative language, Achebe explores themes of cultural identity, imperialism, and the impact of change on individual and collective lives.', NULL),
(40, 'Ficciones', 'Jorge Luis Borges', 'Ficciones is a collection of short stories written by Jorge Luis Borges, considered one of the most influential writers of the 20th century. The stories are characterized by their intricate structure, labyrinthine plots, and philosophical themes that explore concepts such as time, identity, and reality. Borges often blurs the line between fact and fiction, challenging the readers perception of what is real and what is imagined.', NULL),
(41, 'Zorba the Greek', 'Nikos Kazantzakis', 'Zorba the Greek is a novel by Nikos Kazantzakis that tells the story of a young, intellectual man who leaves his home in Crete to manage a mine on a remote Greek island. There, he meets a charismatic and free-spirited man named Zorba, who teaches him to embrace lifes pleasures and live in the moment. The novel delves into themes of love, freedom, and the clash between traditional and modern ways of life in Greece. It is a powerful exploration of the human spirit and the pursuit of happiness.', NULL),
(42, 'The Death of Ivan Ilych', 'Leo Tolstoy', 'The Death of Ivan Ilych is a novella by Leo Tolstoy that tells the story of a high court judge who becomes terminally ill and confronts the inevitability of his own mortality. Ivan Ilych had always lived a conventional and self-satisfied life, but as he faces his imminent death, he comes to realize the emptiness of his existence and the importance of human compassion and understanding. The novella is a powerful exploration of the human condition, the meaning of life, and the nature of suffering.', NULL),
(43, 'Middlemarch', 'George Eliot', 'Middlemarch is a novel by George Eliot that follows the lives of several characters in the small town of Middlemarch, England during the early 19th century. The novel is a portrait of the town and its people, including the idealistic Dorothea Brooke, the ambitious doctor Tertius Lydgate, and the wealthy landowner Nicholas Bulstrode. Eliot weaves together their stories with themes of marriage, politics, and social change to create a nuanced and realistic portrayal of English society.', NULL),
(44, 'Midnight\s Children', 'Salman Rushdie', 'novel by Salman Rushdie that tells the story of Saleem Sinai, a man born at the exact moment of Indias independence from British rule. Saleem possesses magical powers that connect him to the other children born during that hour, and through their stories, Rushdie chronicles the tumultuous history of Indias early years as a sovereign nation. The novel explores themes of identity, memory, and the consequences of political upheaval on individual lives.', NULL),
(45, 'Journey to the End of the Night', 'Louis-Ferdinand Céline', 'Journey to the End of the Night is a novel written by Louis-Ferdinand Céline that tells the story of a man named Ferdinand Bardamu who leaves his hometown of Paris to fight in World War I and later travels to Africa and America. Along the way, Bardamu encounters a series of grotesque and absurd characters and experiences the brutal realities of war and colonialism. The novel is known for its dark humor, vivid language, and exploration of the human condition in a chaotic and meaningless world.', NULL),
(46, 'The Epic of Gilgamesh', 'Anonymous', 'The Epic of Gilgamesh is an ancient poem from Mesopotamia that tells the story of Gilgamesh, a king who embarks on a quest for immortality after the death of his friend Enkidu. Along the way, Gilgamesh battles monsters and faces trials, ultimately learning valuable lessons about the nature of life and death. The poem explores themes of friendship, mortality, and the search for meaning, and is considered one of the earliest known works of literature.', NULL),
(47, 'A Doll\s House', 'Henrik Ibsen', 'play written by Henrik Ibsen that tells the story of Nora Helmer, a housewife who realizes the suffocating nature of her marriage and societys expectations for women. As Nora tries to break free from her husbands control and find her own identity, she faces the harsh consequences of her actions. The play explores themes of gender roles, societal expectations, and the true nature of love and relationships. It is considered a landmark work of feminist literature.', NULL),
(48, 'Invisible Man', 'Ralph Ellison', 'Invisible Man is a novel written by Ralph Ellison that tells the story of a young African-American man living in New York City who is struggling to find his place in society. After being expelled from college, he takes a job at a paint factory where he accidentally becomes the test subject for a dangerous experiment. The experience leaves him feeling invisible and disconnected from the world around him. The novel explores themes of race, identity, and the struggle for self-discovery in a society that often ignores and oppresses those who are different.', NULL),
(49, 'Leaves of Grass', 'Walt Whitman', 'Leaves of Grass is a poetry collection written by Walt Whitman. First published in 1855 and revised and expanded throughout his life, it is considered one of the most important works of American literature. The poems celebrate the beauty of nature, the joys and sorrows of life, and the dignity of the individual. Whitmans use of free verse and unconventional themes and subject matter broke with traditional poetic forms of his time and helped establish a uniquely American voice in literature.', NULL),
(50, 'The Man Without Qualities', 'Robert Musil', 'The Man Without Qualities is a novel written by Robert Musil that takes place in Vienna in 1913, just before the outbreak of World War I. The protagonist, Ulrich, is a mathematician and intellectual who feels disconnected from the society around him. He becomes involved in a project to organize a celebration for the 70th anniversary of the reign of Emperor Franz Joseph, but struggles to find a meaningful purpose for the event. The novel explores themes of identity, morality, and the decline of traditional values in modern society.', NULL),
(51, 'The Magic Mountain', 'Thomas Mann', 'The Magic Mountain is a novel written by Thomas Mann that tells the story of Hans Castorp, a young man who goes to visit his cousin at a sanatorium in the Swiss Alps and ends up staying for seven years. While there, he becomes embroiled in philosophical and intellectual discussions with fellow patients, and falls in love with a woman who is dying of tuberculosis. The novel explores themes of time, mortality, and the clash between the rational and irrational in early 20th century Europe.', NULL),
(52, 'The Book of Disquiet', 'Fernando Pessoa', 'The Book of Disquiet is a literary work by Fernando Pessoa, a Portuguese writer, that is a collection of fragments and reflections on life, existence, and the human condition. The book is written in the form of a diary and the entries are attributed to a semi-autobiographical character named Bernardo Soares. Through Soares musings, Pessoa explores themes of solitude, creativity, identity, and the search for meaning in a constantly changing world. The work is often regarded as one of the most important works of modernist literature.', NULL),
(53, 'Hunger', 'Knut Hamsun', 'Hunger is a novel by Norwegian author Knut Hamsun, published in 1890. It follows the story of an unnamed narrator living in poverty in Oslo and struggling to make a living as a writer. As he experiences increasing physical and mental deterioration from starvation, he grapples with feelings of desperation and alienation from society. The novel is a powerful portrayal of the human experience of hunger and the devastating effects of poverty on the individual psyche.', NULL),
(54, 'The Decameron', 'Giovanni Boccaccio', 'The Decameron is a collection of 100 novellas written by Giovanni Boccaccio in the 14th century. The stories are framed within a narrative of ten characters who flee Florence during the Black Death and tell each other stories to pass the time. The tales range from bawdy comedies to tragic romances and provide a rich portrait of Italian society during the Middle Ages. The books themes include love, death, fortune, and the human condition, and it remains a seminal work of Italian literature.', NULL),
(55, 'Dead Souls', 'Nikolai Gogol', 'Dead Souls is a novel written by Nikolai Gogol that tells the story of a man named Chichikov who travels through the Russian countryside, buying up the "dead souls" of serfs who have died but are still listed on the census as being alive. Chichikov hopes to use these souls as collateral to secure a loan, but his schemes are complicated by the greed and corruption of the local officials he encounters. The novel is a satire of Russian society and explores themes of greed, corruption, and the struggle for identity in a rapidly changing world.', NULL),
(56, 'Metamorphoses', 'Ovid', 'Metamorphoses is a narrative poem by the Roman poet Ovid, which chronicles the history of the world from its creation to the deification of Julius Caesar. The work is divided into fifteen books and features over 250 myths, each focusing on a transformation of some kind. The central theme of the poem is change, both physical and emotional, and the power of transformation to both inspire and terrify. The tales include stories of love and betrayal, heroic deeds and tragic endings, all united by Ovids poetic skill and vivid imagination.', NULL),
(57, 'The Aeneid', 'Virgil', 'The Aeneid is an epic poem written by the Roman poet Virgil that tells the story of the Trojan hero Aeneas and his journey to Italy, where he establishes a new homeland for his people. Along the way, he faces many challenges, including a series of battles with enemies and a descent into the underworld, where he learns about the fate of his ancestors. The poem explores themes of duty, destiny, and the relationship between the individual and the state. It has been widely studied and admired for its literary and historical significance.', NULL),
(58, 'The Castle', 'Franz Kafka', 'The Castle is a novel written by Franz Kafka that follows the story of a land surveyor named K. who arrives in a village to perform a job but struggles to gain access to the mysterious castle that governs the town. As he navigates the confusing bureaucracy and social norms of the village, K. begins to question the purpose and meaning of his own existence. The novel explores themes of power, alienation, and the absurdity of modern society.', NULL),
(59, 'Mahabharata', 'Anonymous', 'Mahabharata is an epic poem from ancient India, with over 100,000 couplets, telling the story of a dynastic struggle for the throne of Hastinapura, culminating in the war of Kurukshetra. It features heroes and villains, gods and demons, and explores complex themes such as duty, fate, and morality. The Bhagavad Gita, a revered Hindu scripture, is also a part of the Mahabharata.', NULL),
(60, 'Wuthering Heights', 'Emily Brontë', 'Wuthering Heights is a novel by Emily Bronte that follows the story of the Earnshaw family and their relationships with the mysterious Heathcliff, an orphan boy they take in. The novel is set in the bleak and windswept Yorkshire moors, and explores themes of love, revenge, and the destructive nature of obsession. Through vivid and powerful writing, Bronte creates a haunting tale of passion and tragedy that has become a classic of English literature.', NULL),
(61, 'Medea', 'Euripides', 'Medea is a Greek tragedy written by Euripides in 431 BC. It tells the story of Medea, a former princess of Colchis, who is abandoned by her husband, Jason, for a younger woman. Medea seeks revenge by killing Jasons new bride and her own children, ultimately becoming a tragic figure consumed by her own anger and despair. The play explores themes of betrayal, revenge, and the consequences of unchecked passion. It continues to be a powerful and thought-provoking work in modern times.', NULL),
(62, 'Gargantua and Pantagruel', 'François Rabelais', 'Gargantua and Pantagruel is a satirical novel by Francois Rabelais, written in the 16th century. It follows the adventures of the giant Gargantua and his son Pantagruel, as they travel through France and encounter various absurd characters and situations. The book is known for its bawdy humor, literary puns, and criticism of religious and political institutions.', NULL),
(63, 'Franz Kafka: The Complete Stories', 'Franz Kafka', 'Franz Kafka: The Complete Stories is a collection of all of Kafkas published and unpublished short stories, showcasing his unique style and themes of alienation, bureaucracy, and existential anxiety. The book includes famous works such as The Metamorphosis and The Trial, as well as lesser-known gems that delve into the depths of the human psyche. With masterful storytelling and haunting imagery, Kafkas stories continue to captivate readers and leave a lasting impression on literature.', NULL),
(64, 'The Red and the Black', 'Stendhal', 'The Red and the Black is a novel written by French author Stendhal, first published in 1830. It tells the story of Julien Sorel, a young man from a humble background who desires to rise up in society by any means necessary. He navigates his way through the political and social hierarchy of early 19th century France, engaging in affairs with older women and attempting to gain the favor of those in power. The novel explores themes of ambition, class, love, and morality, and is considered a classic of French literature.', NULL),
(65, 'Père Goriot', 'Honoré de Balzac', 'Père Goriot is a novel by French author Honoré de Balzac, first published in 1835. The story is set in Paris and follows the lives of various characters, including the titular character, a retired vermicelli maker who sacrifices everything for his two daughters. The novel explores themes of wealth, social status, and the harsh realities of urban life in 19th century Paris. Through its vivid portrayal of characters and their struggles, "Père Goriot" has become a classic of French literature.', NULL),
(66, 'Selected Stories of Anton Chekhov', 'Anton Chekhov', 'The Selected Stories of Anton Chekhov is a collection of some of the greatest works of the renowned Russian writer. With a masterful use of language and an unparalleled ability to capture the complexities of human nature, Chekhovs stories explore themes of love, loss, and the human condition. The collection includes some of his most famous stories, such as The Lady with the Dog and The Darling, as well as lesser-known gems that showcase Chekhovs talent for crafting unforgettable characters and poignant narratives. Through his stories, Chekhov illuminates the joys and sorrows of life, and his work remains as powerful and relevant today as it was when it was first written.', NULL),
(67, 'The Tin Drum', 'Günter Grass', 'The Tin Drum is a novel by Günter Grass, set in Danzig, Germany, before and during World War II. It follows the life of Oskar Matzerath, a boy who decides to stop growing at the age of three and communicates with the world through his tin drum. The book explores themes such as the rise of Nazism, individual identity, and the power of storytelling. It is considered a masterpiece of 20th-century German literature and won the Nobel Prize for Literature in 1999.', NULL),
(68, 'Absalom, Absalom!', 'William Faulkner', 'Absalom, Absalom! is a novel written by William Faulkner and published in 1936. It tells the story of Thomas Sutpen, a man who rises from poverty to become a wealthy plantation owner in Mississippi, but ultimately loses everything due to his own obsessive and destructive ambitions. The novel is known for its complex narrative structure, as well as its themes of race, history, and the South.', NULL),
(69, 'Buddenbrooks: The Decline of a Family', 'Thomas Mann', 'Buddenbrooks is a novel by Thomas Mann, depicting the decline of a wealthy family over four generations. Set in the northern German town of Lübeck, the book explores themes of capitalism, social change, and the tensions between tradition and modernity. The story follows the familys rise to prominence in the 19th century, their struggles to maintain their wealth and status in the face of changing times, and the gradual disintegration of their values and way of life. Through vivid characterization and detailed historical context, Mann paints a poignant and powerful portrait of a familys decline and the forces that shape their fate.', NULL),
(70, 'Ramayana', 'Vālmīki', 'Ramayana is an epic tale of adventure, love, and honor that has been passed down through generations in South Asia. It tells the story of Prince Rama, who, with the help of his loyal friends and his divine wife Sita, battles demons and evil forces to rescue Sita from the clutches of the demon king Ravana. Along the way, the characters encounter numerous challenges and learn valuable lessons about morality, duty, and devotion. The Ramayana is a revered classic in Hinduism and is considered one of the greatest works of ancient Indian literature.', NULL),
(71, 'The Adventures of Huckleberry Finn', 'Mark Twain', 'The Adventures of Huckleberry Finn is a novel by Mark Twain that follows the journey of a young boy named Huck Finn and his friend Jim, a runaway slave, as they escape their respective circumstances and embark on a rafting adventure down the Mississippi River. Along the way, they encounter various obstacles and characters that challenge their perceptions of morality and society, ultimately leading Huck to question the values and beliefs he has been taught. The novel is known for its commentary on racism and social injustice, and is considered a classic of American literature.', NULL),
(72, 'Sons and Lovers', 'D.H. Lawrence', 'Sons and Lovers is a novel by D.H. Lawrence, published in 1913. The story follows the life of Paul Morel, a young man growing up in a working-class family in Nottinghamshire, England. He is torn between his love for his mother and his desire for independence, as well as his conflicting feelings towards the women in his life. The novel explores themes of family, sexuality, and self-discovery, and is considered a masterpiece of modernist literature.', NULL),
(73, 'Demons', 'Fyodor Dostoevsky', 'Demons is a novel by Fyodor Dostoevsky, originally published in 1871-1872. It explores themes of political radicalism, nihilism, and the corrupting influence of power. Set in 19th-century Russia, the story follows a group of intellectuals as they plot to overthrow the government and bring about a new era of freedom. The novel is known for its complex characters, philosophical depth, and powerful social commentary.', NULL),
(74, 'Pedro Páramo', 'Juan Rulfo', 'Pedro Páramo is a novel written by Mexican author Juan Rulfo. It tells the story of Juan Preciado, who travels to his hometown of Comala to find his father, Pedro Páramo, and discovers a town haunted by the memories of its past. The novel explores themes of death, love, and the impact of the past on the present, and is considered a masterpiece of Mexican literature.', NULL),
(75, 'Memoirs of Hadrian', 'Marguerite Yourcenar', 'Memoirs of Hadrian is a historical novel by Marguerite Yourcenar, written as a first-person reflection of the Roman Emperor Hadrian. The book explores Hadrians personal and political life, his philosophical musings, and his struggles to maintain power in the midst of war and rebellion. Yourcenars vivid writing style and detailed portrayal of the ancient world have made the book a classic of historical fiction, acclaimed for its depth of insight into the complexities of the human experience.', NULL),
(76, 'The Book of Job', 'Anonymous', 'The Book of Job is a biblical text found in the Old Testament that tells the story of a man named Job who undergoes severe suffering and tests of faith. Despite losing everything, including his family and possessions, Job remains steadfast in his devotion to God. The book explores themes of suffering, faith, and the nature of Gods justice. It is considered a literary masterpiece and has been studied and interpreted by scholars and theologians for centuries.', NULL),
(77, 'The Golden Notebook', 'Doris Lessing', 'The Golden Notebook is a novel by Doris Lessing that follows the life of Anna Wulf, a writer struggling to reconcile her personal and political beliefs. The book is divided into four notebooks, each representing a different aspect of Annas life, including her relationships, her experiences as a Communist, and her struggles with mental health. Through Annas story, Lessing explores themes of feminism, identity, and the impact of politics on individual lives.', NULL),
(78, 'Molloy / Malone Dies / The Unnamable', 'Samuel Beckett', 'The trilogy Molloy / Malone Dies / The Unnamable is a challenging and experimental work by the Irish author Samuel Beckett. The books follow three different characters, each struggling with the limitations of language, memory, and identity. The narrative is fragmented, non-linear, and often surreal, blurring the lines between reality and imagination. Becketts sparse and minimalist writing style adds to the sense of isolation and despair that permeates the trilogy. Overall, these books are a unique and thought-provoking exploration of the human condition, full of dark humor and existential musings.', NULL),
(79, 'مثنوی معنوی', 'Rumi', 'Masnavi-i Manavi or Mathnawi is a poetic masterpiece written by the 13th century Persian poet and mystic, Jalal ad-Din Muhammad Rumi. Composed of six volumes, it is a collection of spiritual and moral stories, parables, and anecdotes that offer guidance on the path of Sufism and the search for truth and enlightenment. Its lyrical language and profound insights have made it a beloved and influential work of literature throughout the Islamic world and beyond.', NULL),
(80, 'The Complete Essays', 'Michel de Montaigne', 'The Complete Essays is a collection of Michel de Montaignes personal reflections on a variety of topics, including politics, philosophy, and human nature. Written in the 16th century, Montaignes essays are characterized by their informal, conversational style and their willingness to delve into the authors own thoughts and experiences. The collection is considered a masterpiece of French Renaissance literature and a seminal work in the development of the modern essay form.', NULL),
(81, 'Jacques the Fatalist', 'Denis Diderot', 'Jacques the Fatalist is a novel by Denis Diderot, first published in 1796. The book is a philosophical work that explores themes of free will, determinism, and the unpredictability of life. It tells the story of Jacques and his master, as they journey through France and engage in discussions about life, love, and the nature of reality. The novel is known for its nonlinear narrative structure and its use of metafictional elements.', NULL),
(82, 'The Life and Opinions of Tristram Shandy, Gentleman', 'Laurence Sterne', 'The Life and Opinions of Tristram Shandy is a novel by Laurence Sterne, first published in 1759. It is a humorous and experimental work, following the life of the eponymous protagonist and his eccentric family. The novel is known for its digressions and unconventional narrative structure, as well as its bawdy humor and satirical commentary on society and literature. It has had a significant influence on the development of the modern novel and remains a classic of English literature.', NULL),
(83, 'Season of Migration to the North', 'Tayeb Salih', 'Season of Migration to the North is a novel by Sudanese author Tayeb Salih, originally published in Arabic in 1966. The story follows the return of the protagonist, Mustafa Saeed, to his native village in Sudan after spending years in Europe. Through Mustafas narration, the novel explores themes of cultural identity, colonialism, and the complexity of human relationships. The book is widely regarded as a masterpiece of modern Arabic literature and has been translated into several languages.', NULL),
(84, 'The Tale of Genji', 'Murasaki Shikibu', 'The Tale of Genji is a Japanese classic written in the 11th century by Murasaki Shikibu. It follows the life and romantic pursuits of the nobleman Genji and explores themes of love, loss, beauty, and the fleeting nature of life. Considered one of the greatest works of Japanese literature, it is notable for its complex characters, intricate plot, and poetic prose.', NULL),
(85, 'Sentimental Education', 'Gustave Flaubert', 'Sentimental Education is a novel by French author Gustave Flaubert. Set in mid-19th century France, it follows the life of Frederic Moreau, a young man from a middle-class family, as he navigates his way through a series of love affairs and social situations. The novel provides a vivid portrayal of French society during the Second Empire and explores themes such as love, politics, and social class. Despite its initial critical reception, Sentimental Education is now considered a masterpiece of realist literature and an important work in the development of the modern novel.', NULL),
(86, 'أولاد حارتنا', 'Naguib Mahfouz', ' أولاد حارتنا is a classic Arabic novel written by Naguib Mahfouz, set in Cairos Old Quarter in the early 20th century. It tells the story of the residents of a small alley and their daily struggles, aspirations, and relationships. The novel portrays the social and cultural dynamics of the time and addresses themes such as love, family, poverty, and social injustice. Through its vivid characters and captivating storytelling, the book offers a glimpse into the complex and colorful world of the Egyptian capitals urban poor.', NULL),
(87, 'Independent People', 'Halldór Laxness', 'Independent People is a novel by Icelandic author Halldór Laxness, published in 1934. The story follows Bjartur, a sheep farmer, who is determined to be independent and stubbornly insists on working his land without help or compromise. He struggles to maintain his freedom while dealing with the harsh realities of life in rural Iceland, including poverty, natural disasters, and family drama. The novel explores themes of isolation, pride, and the complex relationship between humans and nature.', NULL),
(88, 'The Sound of the Mountain', 'Yasunari Kawabata', 'The Sound of the Mountain is a novel by Yasunari Kawabata that explores the complex relationships within a Japanese family. The story centers around Ogata Shingo, an aging man who reflects on his life and the disappointments he has experienced. As he struggles to come to terms with his past, he finds solace in his granddaughter, whose innocence and youth bring him hope for the future. Through Shingos introspective journey, Kawabata delves into themes of aging, family, and the human condition.', NULL),
(89, 'Diary of a Madman and Other Stories', 'Lu Xun', 'Diary of a Madman and Other Stories is a collection of short stories by the famous Chinese author Lu Xun. Published in 1918, it includes the iconic story "Diary of a Madman" which is considered a masterpiece of modern Chinese literature. The stories explore themes such as the oppressive nature of tradition and the struggles of individuals in a rapidly changing society. Lu Xuns writing style is poignant and thought-provoking, making this collection a must-read for anyone interested in Chinese literature or the human condition.', NULL),
(90, 'Zenos Conscience', 'Italo Svevo', 'Zenos Conscience is a novel by Italian author Italo Svevo, first published in 1923. It tells the story of Zeno, a middle-aged businessman in Trieste, Italy, who seeks psychoanalysis to overcome his smoking habit. Through his sessions, Zeno reflects on his past and present, revealing his relationships with his father, wife, and mistress. The novel is known for its stream-of-consciousness style, dark humor, and themes of identity, self-deception, and the human condition.', NULL),
(91, 'Nostromo', 'Joseph Conrad', 'Nostromo is a novel written by Joseph Conrad and published in 1904. Set in a fictional South American country, it follows the story of an Italian sailor named Nostromo and the various characters whose lives are intertwined with his. The novel explores themes of imperialism, greed, betrayal, and the corrupting influence of power. Through its complex narrative structure and vivid descriptions of the landscape and characters, "Nostromo" remains a classic of English literature.', NULL),
(92, 'Romancero gitano', 'Federico García Lorca', 'Romancero gitano is a book of poetry written by Spanish poet Federico Garcia Lorca. Published in 1928, the collection consists of eighteen narrative poems that draw on traditional Spanish folklore and the Romani culture. Lorcas lyrical and evocative language captures the beauty, passion, and tragedy of the Andalusian landscape and its people, exploring themes of love, death, betrayal, and the struggle for freedom. The Romancero gitano is considered one of Lorcas most significant works and a masterpiece of Spanish literature.', NULL),
(93, 'Grande Sertão: Veredas', 'João Guimarães Rosa', 'Grande Sertão: Veredas is a novel by Brazilian author João Guimarães Rosa, published in 1956. The book is a masterpiece of Brazilian literature and explores themes such as love, violence, power, and the relationship between humans and the natural world. Set in the remote backlands of Brazil, the story is narrated by a semi-literate cowboy named Riobaldo, who tells the tale of his life as an outlaw and his complicated relationship with a fellow outlaw named Diadorim. The novel is renowned for its innovative use of language and its complex narrative structure, which blurs the boundaries between reality and imagination.', NULL),
(94, 'History (La Storia, #1-2)', 'Elsa Morante', 'History (La Storia, #1-2) is a novel written by Italian author Elsa Morante. It follows the life of Ida Ramundo, a poor woman living in Rome during World War II, and her son Useppe as they struggle to survive in the midst of poverty, violence, and political turmoil. The book explores themes of love, loss, hope, and resilience in the face of adversity, and provides a unique and poignant perspective on one of the darkest periods in modern history', NULL),
(95, 'Poems of Paul Celan', 'Paul Celan', 'Poems of Paul Celan is a collection of poetic works by the acclaimed German-language poet, Paul Celan. His poems are known for their powerful imagery and deep themes of loss, memory, and the struggle to find meaning in a world shattered by war. Through his use of language, Celan invites readers to confront the difficult truths of the past and to contemplate the nature of human suffering and resilience.', NULL),
(96, 'Berlin Alexanderplatz', 'Alfred Döblin', 'Berlin Alexanderplatz is a novel by German author Alfred Döblin, first published in 1929. The story follows Franz Biberkopf, a former convict, as he tries to turn his life around in 1920s Berlin. The book is a snapshot of life in the city during a time of social and political upheaval, and explores themes of poverty, crime, and the struggle for survival', NULL),
(97, 'Njal\s Saga', 'Unknown', 'Njals Saga is a medieval Icelandic saga that follows the lives of two friends, Njal and Gunnar, and their families in the 10th and 11th centuries. The saga is known for its vivid descriptions of Viking battles, complex legal disputes, and the themes of revenge, honor, and loyalty. It is considered a masterpiece of medieval Icelandic literature and one of the most important sagas.', NULL),
(98, 'The Recognition of Śakuntalā', 'Kālidāsa', 'The Recognition of Śakuntalā is a play written by the ancient Indian poet and playwright Kalidasa. The story follows the romantic entanglements of King Dushyanta and the beautiful maiden Śakuntalā, who becomes pregnant with his child. However, due to a series of misunderstandings and curses, the couple is separated, and Dushyanta forgets about Śakuntalā entirely. The play explores themes of love, loyalty, and the consequences of forgetting ones past. The Recognition of Śakuntalā is considered a masterpiece of Sanskrit literature and has had a significant influence on Indian art and culture. The play is known for its lyrical language, complex characterization, and intricate plot, making it a timeless classic.', NULL),
(99, 'The Orchard: The Bostan Of Saadi Of Shiraz', 'Saadi', 'The Orchard: The Bostan of Saadi of Shiraz is a classic work of Persian literature written by Saadi, one of the greatest poets of the medieval Islamic world. The book is a collection of short stories and poems, which provide a commentary on various aspects of human life, including love, morality, and wisdom. The stories and poems are filled with vivid imagery and rich symbolism, and they offer a glimpse into the cultural and social milieu of Saadis time. The Orchard is a timeless masterpiece that continues to inspire and delight readers with its lyrical prose and profound insights into the human experience.', NULL),
(100, 'The Poems Of Leopardi', 'Giacomo Leopardi', 'The Poems of Leopardi is a collection of Italian poet Giacomo Leopardis most celebrated works. Known for his deeply introspective and melancholic style, Leopardis poetry explores themes such as love, death, nature, and the human condition. His use of language is both elegant and powerful, and his work is considered a cornerstone of Italian literature. This collection features a selection of his most significant poems, including To Sylvia, The Infinite, and The Lonely Sparrow, among others. Overall, The Poems of Leopardi is a beautiful and thought-provoking read that offers insight into the mind of a gifted poet.', NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `Books`
--
ALTER TABLE `books`
  ADD PRIMARY KEY (`book_id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `Books`
--
ALTER TABLE `books`
  MODIFY `book_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=101;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
